// <auto-generated />
using System;
using Gayrimenkul.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gayrimenkul.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122091432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Gayrimenkul.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Satılık gayrimenkuller",
                            Name = "Satılık"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kiralık gayrimenkuller",
                            Name = "Kiralık"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Devren satılık işyerleri",
                            Name = "Devren"
                        });
                });

            modelBuilder.Entity("Gayrimenkul.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kızılay Mahallesi",
                            Bathrooms = 2,
                            CategoryId = 1,
                            City = "Ankara",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Şehir merkezinde, ulaşıma yakın, yeni yapılı 3+1 daire",
                            District = "Çankaya",
                            Floor = 5,
                            ImageUrl = "https://via.placeholder.com/400x300?text=Daire",
                            IsActive = true,
                            Price = 2500000m,
                            Rooms = 4,
                            SquareMeters = 120,
                            Title = "Merkez Lokasyonda 3+1 Daire",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Çayırhan Yolu",
                            Bathrooms = 3,
                            CategoryId = 1,
                            City = "Ankara",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Geniş bahçeli, müstakil villa. Doğa manzaralı.",
                            District = "Beypazarı",
                            Floor = 2,
                            ImageUrl = "https://via.placeholder.com/400x300?text=Villa",
                            IsActive = true,
                            Price = 5000000m,
                            Rooms = 5,
                            SquareMeters = 250,
                            Title = "Bahçeli 4+1 Villa",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Aktepe Mahallesi",
                            Bathrooms = 1,
                            CategoryId = 2,
                            City = "Ankara",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversiteye yakın, eşyalı kiralık daire",
                            District = "Keçiören",
                            Floor = 3,
                            ImageUrl = "https://via.placeholder.com/400x300?text=Kiralık",
                            IsActive = true,
                            Price = 15000m,
                            Rooms = 3,
                            SquareMeters = 85,
                            Title = "Öğrenci Evi - 2+1 Kiralık",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Gayrimenkul.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo@gayrimenkul.com",
                            FullName = "Demo Kullanıcı",
                            Password = "123456",
                            Phone = "0555 123 4567"
                        });
                });

            modelBuilder.Entity("Gayrimenkul.Models.Property", b =>
                {
                    b.HasOne("Gayrimenkul.Models.Category", "Category")
                        .WithMany("Properties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gayrimenkul.Models.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gayrimenkul.Models.Category", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Gayrimenkul.Models.User", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
